### ISSUE TITLE
[Feat]Add TO-DO list App

### ISSUE THREAD

**Issue by laragupta** [beRajeevKumar/Frontend_Mentor#475]
### Description

using the technologies html,css and javascript . Ican create TO-DO list app which we can add on in this project. it might be helpful for others.

### Screenshots

![image](https://github.com/user-attachments/assets/2bcef427-95e4-4275-a7f5-2ca8b40de45f)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by gourabbistu089** [comment]
i implement this features

**Comment by Shreyas-GN** [comment]
Could you please assign me to the to-do list app issue? I have relevant experience from my role as a Full Stack Developer at TechieAid, where I built a similar app's backend. I’m confident I can contribute with HTML, CSS, and JavaScript.

**Comment by Pariyul** [comment]
Hey do assign this to me
